### ISSUE TITLE
Web server starts running before database server

### ISSUE THREAD

**Issue by emrecalik** [CAKES-coding/swe574-group2#90]
**Describe the bug**
Web server starts running before database server

**Solution**
Add database service as a dependency to web service

**Comment by semihsolmaz** [comment]
added control for connection to db service on 5432, in web service command block 
- "while !</dev/tcp/db/5432; do sleep 3; done"

```yaml
services:
  web:
    image: semihsolmaz/574:latest
    command: bash -c "while !</dev/tcp/db/5432; do sleep 3; done && python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: wikode
    volumes:
      - .:/wikode
```
